# Built with Jekyll 3.2.0

# Setup
title:               Theories of Quantum Matter
tagline:             'Quantum Mechanics of Many Body Systems'
description:         'A Part III Physics Course at the University of Cambridge'
url:                 'http://tqm.usertest.mws3.csx.cam.ac.uk'
baseurl:             '/Theories-of-Quantum-Matter'

# About/contact
author:
  name:              Austen Lamacraft
  url:               http://www.tcm.phy.cam.ac.uk/profiles/al200/
  email:             al200@cam.ac.uk

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  lectures:
    output: true
    permalink: /lectures/:path/
  problems:
    output: true
    permalink: /problems/:path/

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]

gems: ['jekyll/scholar']
